# hyprpaper (0.8+): block-based wallpaper config

wallpaper {
	monitor = 
	path = /home/tripathiji/.config/hypr/wallpaper/urban-vintage-78A265wPiO4-unsplash.jpg
	fit_mode = cover
}

# Enable IPC for scripts
ipc = true