# hyprpaper (0.8+): block-based wallpaper config

wallpaper {
	monitor = 
	path = /home/tripathiji/.config/hypr/wallpaper/a_white_lines_on_a_black_background.jpeg
	fit_mode = cover
}

# Enable IPC for scripts
ipc = true