# hyprpaper (0.8+): block-based wallpaper config

wallpaper {
	monitor = 
	path = /home/tripathiji/.config/hypr/wallpaper/a_colorful_swirls_of_paint.jpg
	fit_mode = cover
}

# Enable IPC for scripts
ipc = true