local M = {}

M.name = "animations"
M.lines = {
    "animations {",
    "    enabled = true",
    "    workspace_wraparound = true",
    "",
    "    bezier = fluent_decel, 0.1, 1, 0, 1",
    "    bezier = fluent_accel, 0.1, 0, 0.1, 0",
    "    bezier = wind, 0.05, 0.9, 0.1, 1.05",
    "    bezier = winIn, 0.1, 1.1, 0.1, 1.1",
    "    bezier = winOut, 0.3, -0.3, 0, 1",
    "    bezier = liner, 1, 1, 1, 1",
    "    bezier = linear, 0, 0, 1, 1",
    "",
    "    # --- SPRING-approx curves (cubic-bezier approximations) ---",
    "    bezier = spring_menu, 0.20, 1.20, 0.30, 1.00",
    "    bezier = spring_window, 0.10, 0.90, 0.20, 1.05",
    "    bezier = spring_open, 0.10, 0.90, 0.20, 1.05",
    "    bezier = spring_workspace, 0.08, 0.95, 0.12, 1.05",
    "    bezier = spring_special, 0.10, 0.90, 0.20, 1.05",
    "",
    "    animation = windowsIn, 1, 2, spring_open, slide",
    "    animation = windowsOut, 1, 2, fluent_accel, slide",
    "    animation = windowsMove, 1, 2, spring_window, slide",
    "",
    "    animation = border, 1, 6, linear",
    "    animation = borderangle, 1, 60, linear, once",
    "",
    "    animation = fadeIn, 1, 2, fluent_decel",
    "    animation = fadeOut, 1, 2, fluent_accel",
    "    animation = fadeSwitch, 1, 2, fluent_decel",
    "    animation = fadeShadow, 1, 2, fluent_decel",
    "    animation = fadeDim, 1, 3, fluent_decel",
    "",
    "    animation = workspaces, 1, 4, spring_workspace, slide",
    "    animation = workspacesIn, 1, 4, spring_workspace, slide",
    "    animation = workspacesOut, 1, 4, fluent_accel, slide",
    "    animation = specialWorkspace, 1, 4, spring_special, slidevert",
    "",
    "    animation = layers, 1, 2, fluent_decel, slide",
    "    animation = layersIn, 1, 2, spring_menu, slide",
    "    animation = layersOut, 1, 2, fluent_accel, slide",
    "    animation = fadeLayersIn, 1, 2, fluent_decel",
    "    animation = fadeLayersOut, 1, 2, fluent_accel",
    "",
    "    animation = zoomFactor, 1, 4, fluent_decel",
    "}",
}

return M
