local M = {}

M.name = "animations"
M.lines = {
    "animations {",
    "    enabled = true",
    "    workspace_wraparound = true",
    "",
    "    # ═══════════════════════════════════════════════════════════════════",
    "    # │ BEZIER CURVES                                                  │",
    "    # ═══════════════════════════════════════════════════════════════════",
    "",
    "    # --- Fluent Design Curves (Windows 11) ---",
    "    bezier = fluent_decel, 0.1, 1, 0, 1",
    "    bezier = fluent_accel, 0.1, 0, 0.1, 0",
    "",
    "    # --- Spring-Approximating Curves (Cubic-bezier) ---",
    "    # Snappy with micro-overshoot — feels alive without being distracting",
    "    bezier = spring_snappy, 0.15, 1.12, 0.28, 1.00",
    "    # Bouncy overshoot — for elements that should feel playful",
    "    bezier = spring_bouncy, 0.05, 0.90, 0.10, 1.15",
    "    # Cinematic ease — slower, heavier feel for workspace transitions",
    "    bezier = spring_cinematic, 0.08, 0.95, 0.12, 1.05",
    "    # Menu/popup ease — fast reveal with smooth settle",
    "    bezier = spring_menu, 0.20, 1.20, 0.30, 1.00",
    "",
    "    # --- Utility Curves ---",
    "    bezier = linear, 0, 0, 1, 1",
    "    bezier = smooth_out, 0.36, 0, 0.66, -0.56",
    "    bezier = smooth_in, 0.25, 1, 0.5, 1",
    "",
    "    # ═══════════════════════════════════════════════════════════════════",
    "    # │ WINDOW ANIMATIONS                                              │",
    "    # ═══════════════════════════════════════════════════════════════════",
    "",
    "    # Pop-in from 80% scale with spring overshoot — premium open feel",
    "    animation = windowsIn, 1, 3, spring_bouncy, popin 80%",
    "    # Quick slide out — windows shouldn't linger when closing",
    "    animation = windowsOut, 1, 2, fluent_accel, popin 80%",
    "    # Smooth spring movement for drag/resize/tiling changes",
    "    animation = windowsMove, 1, 3, spring_snappy",
    "",
    "    # ═══════════════════════════════════════════════════════════════════",
    "    # │ BORDER ANIMATIONS                                              │",
    "    # ═══════════════════════════════════════════════════════════════════",
    "",
    "    # Smooth gradient color transition on focus change",
    "    animation = border, 1, 4, fluent_decel",
    "    # Gradient angle rotation — 'once' to avoid battery drain",
    "    animation = borderangle, 1, 60, linear, once",
    "",
    "    # ═══════════════════════════════════════════════════════════════════",
    "    # │ FADE ANIMATIONS                                                │",
    "    # ═══════════════════════════════════════════════════════════════════",
    "",
    "    animation = fadeIn, 1, 3, fluent_decel",
    "    animation = fadeOut, 1, 2, fluent_accel",
    "    animation = fadeSwitch, 1, 3, fluent_decel",
    "    animation = fadeShadow, 1, 3, fluent_decel",
    "    animation = fadeDim, 1, 4, fluent_decel",
    "",
    "    # Layer fade control (menus, bars, notifications)",
    "    animation = fadeLayersIn, 1, 2, spring_menu",
    "    animation = fadeLayersOut, 1, 2, fluent_accel",
    "",
    "    # Wayland popup fades (right-click menus, tooltips)",
    "    animation = fadePopupsIn, 1, 2, spring_menu",
    "    animation = fadePopupsOut, 1, 2, fluent_accel",
    "",
    "    # DPMS fade (smooth screen wake/sleep instead of harsh flash)",
    "    animation = fadeDpms, 1, 8, fluent_decel",
    "",
    "    # ═══════════════════════════════════════════════════════════════════",
    "    # │ WORKSPACE ANIMATIONS                                           │",
    "    # ═══════════════════════════════════════════════════════════════════",
    "",
    "    # Slide + fade hybrid — windows slide 20% and crossfade (cinematic)",
    "    animation = workspaces, 1, 4, spring_cinematic, slidefade 20%",
    "    animation = workspacesIn, 1, 4, spring_cinematic, slidefade 20%",
    "    animation = workspacesOut, 1, 4, fluent_accel, slidefade 20%",
    "",
    "    # Special workspace (scratchpad) — vertical slide with bounce",
    "    animation = specialWorkspace, 1, 4, spring_bouncy, slidevert",
    "    animation = specialWorkspaceIn, 1, 4, spring_bouncy, slidevert",
    "    animation = specialWorkspaceOut, 1, 3, fluent_accel, slidevert",
    "",
    "    # ═══════════════════════════════════════════════════════════════════",
    "    # │ LAYER ANIMATIONS (UI elements)                                 │",
    "    # ═══════════════════════════════════════════════════════════════════",
    "",
    "    # Menus/bars pop in with spring overshoot",
    "    animation = layers, 1, 2, spring_menu, popin",
    "    animation = layersIn, 1, 2, spring_menu, popin",
    "    animation = layersOut, 1, 2, fluent_accel, slide",
    "",
    "    # ═══════════════════════════════════════════════════════════════════",
    "    # │ EXTRA ANIMATIONS                                               │",
    "    # ═══════════════════════════════════════════════════════════════════",
    "",
    "    # Smooth zoom transitions",
    "    animation = zoomFactor, 1, 4, spring_snappy",
    "    # Monitor connect/disconnect zoom animation",
    "    animation = monitorAdded, 1, 6, spring_bouncy",
    "}",
}

return M
