local M = {}

M.name = "decorations"
M.lines = {
    "general {",
    "    layout = dwindle",
    "    gaps_in = 4",
    "    gaps_out = 8",
    "    border_size = 1",
    "    resize_on_border = true",
    "    allow_tearing = false",
    "    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg",
    "    col.inactive_border = rgba(595959aa)",
    "",
    "    snap {",
    "        enabled = true",
    "        window_gap = 10",
    "        monitor_gap = 10",
    "        border_overlap = true",
    "    }",
    "}",
    "",
    "group {",
    "    groupbar {",
    "        font_family = Segoe UI Variable Display",
    "        font_size = 11",
    "        text_padding = 8",
    "        text_color = 0xffffffff",
    "        col.active = rgba(33ccffee)",
    "        col.inactive = rgba(595959aa)",
    "    }",
    "}",
    "",
    "decoration {",
    "    rounding = 10",
    "",
    "    blur {",
    "        enabled = true",
    "        new_optimizations = true",
    "        xray = true",
    "        popups = false",
    "        special = false",
    "        size = 6",
    "        passes = 3",
    "        noise = 0.03",
    "        contrast = 1.1",
    "        brightness = 0.9",
    "        vibrancy = 0.4",
    "        vibrancy_darkness = 0.5",
    "        popups_ignorealpha = 0.6",
    "    }",
    "",
    "    shadow {",
    "        enabled = true",
    "        range = 24",
    "        render_power = 4",
    "        color = rgba(0000004D)",
    "        offset = 0 4",
    "    }",
    "",
    "    dim_inactive = true",
    "    dim_strength = 0.04",
    "    dim_special = 0.15",
    "    dim_around = 0.3",
    "}",
    "",
    "windowrule = match:class ^(mpv|vlc|celluloid)$, no_dim on",
    "windowrule = match:fullscreen true, no_dim on",
    "windowrule = match:pin true, no_dim on",
}

return M
