local M = {}

M.name = "decorations"
M.lines = {
    "general {",
    "    layout = dwindle",
    "    gaps_in = 4",
    "    gaps_out = 8",
    "    border_size = 2",
    "    resize_on_border = true",
    "    extend_border_grab_area = 15",
    "    hover_icon_on_border = true",
    "    allow_tearing = true",
    "",
    "    # Animated gradient border — cyan ↔ purple on active, subtle grey on inactive",
    "    col.active_border = rgba(33ccffee) rgba(aa44ffee) 45deg",
    "    col.inactive_border = rgba(3a3a3aaa)",
    "",
    "    snap {",
    "        enabled = true",
    "        window_gap = 10",
    "        monitor_gap = 10",
    "        border_overlap = true",
    "    }",
    "}",
    "",
    "group {",
    "    groupbar {",
    "        font_family = Segoe UI Variable Display",
    "        font_size = 11",
    "        text_padding = 8",
    "        text_color = 0xffffffff",
    "        col.active = rgba(33ccffcc)",
    "        col.inactive = rgba(3a3a3a88)",
    "    }",
    "}",
    "",
    "decoration {",
    "    rounding = 12",
    "",
    "    blur {",
    "        enabled = true",
    "        new_optimizations = true",
    "        xray = true",
    "        popups = false",
    "        special = true",
    "        size = 8",
    "        passes = 3",
    "        noise = 0.02",
    "        contrast = 1.05",
    "        brightness = 0.85",
    "        vibrancy = 0.50",
    "        vibrancy_darkness = 0.40",
    "        popups_ignorealpha = 0.6",
    "    }",
    "",
    "    shadow {",
    "        enabled = true",
    "        range = 30",
    "        render_power = 3",
    "        color = rgba(00000055)",
    "        color_inactive = rgba(00000033)",
    "        offset = 0 6",
    "        scale = 0.97",
    "    }",
    "",
    "    dim_inactive = true",
    "    dim_strength = 0.06",
    "    dim_special = 0.20",
    "    dim_around = 0.35",
    "}",
    "",
    "# --- Smart dimming exceptions ---",
    "windowrule = match:class ^(mpv|vlc|celluloid)$, no_dim on",
    "windowrule = match:fullscreen true, no_dim on",
    "windowrule = match:pin true, no_dim on",
}

return M
