local M = {}

M.name = "settings"
M.lines = {
    "monitor=,preferred,auto,1",
    "",
    "exec-once = xsettingsd",
    "env = HYPRCURSOR_THEME,Bibata-Modern-Ice",
    "env = HYPRCURSOR_SIZE,24",
    "env = XCURSOR_THEME,Bibata-Modern-Ice",
    "env = XCURSOR_SIZE,24",
    "env = GTK_THEME,adw-gtk3-dark",
    "env = QT_QPA_PLATFORM,wayland;xcb",
    "env = QT_QPA_PLATFORMTHEME,qt5ct",
    "env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1",
    "env = XDG_CURRENT_DESKTOP,Hyprland",
    "env = XDG_SESSION_TYPE,wayland",
    "env = XDG_SESSION_DESKTOP,Hyprland",
    "",
    "input {",
    "    kb_layout = us",
    "    numlock_by_default = true",
    "    follow_mouse = 1",
    "    mouse_refocus = true",
    "    focus_on_close = 0",
    "    float_switch_override_focus = 1",
    "",
    "    touchpad {",
    "        natural_scroll = true",
    "        disable_while_typing = true",
    "        tap-to-click = true",
    "        drag_lock = 0",
    "        tap-and-drag = true",
    "        scroll_factor = 1.0",
    "        middle_button_emulation = false",
    "        clickfinger_behavior = false",
    "    }",
    "",
    "    sensitivity = 0.2",
    "    accel_profile = \"\"",
    "    scroll_factor = 1.0",
    "    repeat_rate = 25",
    "    repeat_delay = 600",
    "}",
    "",
    "dwindle {",
    "    preserve_split = true",
    "    smart_split = false",
    "    smart_resizing = false",
    "    precise_mouse_move = true",
    "}",
    "",
    "layout {",
    "    single_window_aspect_ratio = 0 0",
    "    single_window_aspect_ratio_tolerance = 0.1",
    "}",
    "",
    "scrolling {",
    "    fullscreen_on_one_column = true",
    "    column_width = 0.85",
    "    focus_fit_method = 1",
    "    follow_focus = true",
    "    follow_min_visible = 0.4",
    "    explicit_column_widths = 0.333, 0.5, 0.667, 1.0",
    "    direction = right",
    "}",
    "",
    "render {",
    "    direct_scanout = 2",
    "    new_render_scheduling = true",
    "}",
    "",
    "xwayland {",
    "    enabled = true",
    "    use_nearest_neighbor = true",
    "    force_zero_scaling = false",
    "}",
    "",
    "binds {",
    "    scroll_event_delay = 300",
    "    workspace_back_and_forth = false",
    "    workspace_center_on = 0",
    "    focus_preferred_method = 0",
    "    allow_workspace_cycles = false",
    "    ignore_group_lock = false",
    "    movefocus_cycles_fullscreen = false",
    "    drag_threshold = 0",
    "}",
    "",
    "gestures {",
    "    gesture = 3, horizontal, workspace",
    "    gesture = 3, down, special, term",
    "    gesture = 3, up, fullscreen, maximize",
    "    gesture = 4, left, dispatcher, layoutmsg, move +col",
    "    gesture = 4, right, dispatcher, layoutmsg, move -col",
    "    gesture = 4, pinchout, cursorZoom, 1.15 mult",
    "    gesture = 4, pinchin, cursorZoom, 0.87 mult",
    "}",
    "",
    "cursor {",
    "    inactive_timeout = 3",
    "    no_warps = false",
    "    persistent_warps = true",
    "    warp_on_change_workspace = 1",
    "    warp_on_toggle_special = 1",
    "    hide_on_key_press = true",
    "    hide_on_touch = true",
    "    enable_hyprcursor = true",
    "    sync_gsettings_theme = true",
    "    no_hardware_cursors = 2",
    "    no_break_fs_vrr = 2",
    "    min_refresh_rate = 60",
    "    zoom_factor = 1.0",
    "    zoom_rigid = false",
    "    zoom_detached_camera = true",
    "    zoom_disable_aa = false",
    "}",
    "",
    "misc {",
    "    disable_hyprland_logo = true",
    "    disable_splash_rendering = true",
    "    vrr = 2",
    "}",
    "",
    "group {",
    "    auto_group = true",
    "    insert_after_current = true",
    "    focus_removed_window = true",
    "    drag_into_group = 2",
    "    merge_groups_on_drag = true",
    "    merge_groups_on_groupbar = true",
    "    col.border_active = 0x66ffff00",
    "    col.border_inactive = 0x66777700",
    "    col.border_locked_active = 0x66ff5500",
    "    col.border_locked_inactive = 0x66775500",
    "}",
    "",
    "exec-once = [workspace special:term silent] kitty --class scratchpad",
    "# exec-once = [workspace special:music silent] spotify",
    "# exec-once = [workspace special:files silent] thunar",
    "",
    "windowrule = match:class ^(scratchpad)$, float on",
    "windowrule = match:class ^(scratchpad)$, size (monitor_w*0.80) (monitor_h*0.80)",
    "windowrule = match:class ^(scratchpad)$, center on",
    "windowrule = match:class ^(scratchpad)$, opacity 0.95 0.9",
    "",
    "workspace = 1, persistent:true, name:main",
    "workspace = 2, persistent:true, name:code",
    "workspace = 3, persistent:true, name:browser",
    "",
    "# workspace = 1, monitor:DP-1, default:true",
    "# workspace = 2, monitor:DP-1",
    "# workspace = 3, monitor:DP-1",
    "# workspace = 4, monitor:HDMI-A-1, default:true",
    "# workspace = 5, monitor:HDMI-A-1",
    "",
    "# windowrule = match:class ^(steam_app_).*, content game",
    "# windowrule = match:class ^(mpv|vlc|celluloid)$, content video",
    "# windowrule = match:title ^(.*YouTube.*)$, content video",
    "# windowrule = match:class ^(gimp|krita|inkscape)$, content photo",
}

return M
