#################
### AUTOSTART ###
#################

# Start essential services
exec-once = waybar
exec-once = hypridle
exec-once = dunst
exec-once = nm-applet --indicator

# Start background scripts and services
# Start the wallpaper script in the background, redirecting ALL output to /dev/null
# This prevents the script from being suspended and fixes the "tty output" error.
# exec-once = ~/.config/hypr/scripts/wallpaper.sh > /dev/null 2>&1 &
exec-once = ~/.config/hypr/scripts/startup_theme.sh
exec-once = wl-paste --watch cliphist store
exec-once = /home/tripathiji/.config/dunst/battery_notification.sh # Assumes the script handles its own loop
exec-once = ~/.config/dunst/battery_notification.sh
# Start desktop portals and authentication agents
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec-once = /usr/lib/xdg-desktop-portal-hyprland
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Optional: if you use KDE Wallet
exec-once = /usr/lib/pam_kwallet_init
# Starts the Hyprland-specific portal
exec-once = /usr/lib/xdg-desktop-portal-hyprland

# Starts the GTK portal as a fallback for file pickers, etc.
# The system will automatically use this when needed.
exec-once = /usr/lib/xdg-desktop-portal-gtk